Update neutral_example.yml

diff --git a/.github/workflows/neutral_example.yml b/.github/workflows/neutral_example.yml
--- a/.github/workflows/neutral_example.yml
+++ b/.github/workflows/neutral_example.yml
@@ -1,5 +1,4 @@
 name: Neutral Status Workflow
-run-name: Run name for workflow
 on: workflow_dispatch
 
 jobs:
@@ -11,7 +10,8 @@ jobs:
       - name: Run potentially failing script
         run: |
           echo "This script might fail..."
-          #exit 78 # Simulate a failure
+          exit 78 # Simulate a failure
+          continue-on-error: true
 
       # Add another step to confirm the workflow continues
       - name: Final step
